catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.20
  vite-plus: ^0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.20
packages:
  - 'packages/*'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - prisma
  - sharp
  - vue-demi
  - workerd
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
