-- 🔒 LOCKED — managed by clade sync-evlog-presets.mjs
-- preset: evlog-d-pattern-audit
-- source: vendor/snippets/audit-pattern/migration.sql
-- to: presets/evlog-d-pattern-audit/supabase/migrations/0000_create_audit_logs.sql
-- do not edit consumer-side; modify clade vendor snippet then re-propagate

-- D-pattern Audit Logs 標準 schema
-- Source: clade docs/d-pattern-master-plan.md §2
-- Usage:
--   1. supabase migration new create_audit_logs
--   2. paste 此檔內容
--   3. 視 consumer 需求調整：
--      - single-tenant 可移除 tenant_id 欄位 + per-tenant lock
--      - 既有 audit 表升級走 expand 路徑（見 master plan §8）

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.audit_logs (
  event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid,
  span_id uuid,
  idempotency_key text,
  actor_id uuid,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
  reason text,
  business_keys jsonb NOT NULL DEFAULT '{}'::jsonb,
  prev_hash text,
  hash text NOT NULL,
  evlog_drained_at timestamptz,
  evlog_drain_attempts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.audit_logs IS
  'D-pattern canonical audit outbox. evlog is derived stream; DB row is source of truth.';
COMMENT ON COLUMN public.audit_logs.business_keys IS
  'Structured business keys only. Do not store PII, raw prompts, raw request bodies, or large payloads.';
COMMENT ON COLUMN public.audit_logs.prev_hash IS
  'Previous audit row hash in the same tenant chain.';
COMMENT ON COLUMN public.audit_logs.hash IS
  'SHA-256 hash anchor generated by audit_logs_set_hash().';

CREATE INDEX audit_logs_chain_idx
  ON public.audit_logs (tenant_id, created_at DESC, event_id DESC);

CREATE INDEX audit_logs_target_idx
  ON public.audit_logs (tenant_id, target_type, target_id, created_at DESC);

CREATE INDEX audit_logs_actor_idx
  ON public.audit_logs (tenant_id, actor_id, created_at DESC);

CREATE UNIQUE INDEX audit_logs_idempotency_idx
  ON public.audit_logs (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- 注意：函式標 STABLE 而非 IMMUTABLE。timestamptz `AT TIME ZONE 'UTC'`
-- 在 PostgreSQL 內歸類為 STABLE（依 session 設定），無法 IMMUTABLE。
-- 若要 IMMUTABLE，把 `created_at AT TIME ZONE 'UTC'` 換成
-- `to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.USOF')` 或 epoch microseconds。
CREATE OR REPLACE FUNCTION public.audit_log_hash_payload(r public.audit_logs)
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT concat_ws('|',
    r.event_id::text,
    coalesce(r.tenant_id::text, ''),
    coalesce(r.prev_hash, ''),
    r.action,
    coalesce(r.actor_id::text, ''),
    r.target_type,
    r.target_id,
    r.outcome,
    coalesce(r.reason, ''),
    jsonb_strip_nulls(r.business_keys)::text,
    r.created_at AT TIME ZONE 'UTC'
  )
$$;

CREATE OR REPLACE FUNCTION public.audit_logs_set_hash()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
-- 必須含 `extensions` 才能找到 pgcrypto 的 digest()。Supabase 把 pgcrypto 裝在
-- extensions schema，trigger SET search_path = public 看不到。
SET search_path = public, extensions
AS $$
DECLARE
  chain_key text;
BEGIN
  NEW.event_id := coalesce(NEW.event_id, gen_random_uuid());
  NEW.created_at := coalesce(NEW.created_at, now());
  NEW.business_keys := coalesce(NEW.business_keys, '{}'::jsonb);

  -- chain_key 設計：null tenant 跟字面 'global' tenant 共用同一條 global chain。
  -- single-tenant consumer 可保留 null tenant；multi-tenant consumer 必填 tenant_id。
  -- 若 consumer 需要區分 null 與 'global'，改用 '__global__' 並加 schema constraint。
  chain_key := coalesce(NEW.tenant_id::text, 'global');
  PERFORM pg_advisory_xact_lock(hashtextextended('audit_logs:' || chain_key, 0));

  SELECT al.hash INTO NEW.prev_hash
  FROM public.audit_logs al
  WHERE (al.tenant_id IS NOT DISTINCT FROM NEW.tenant_id)
  ORDER BY al.created_at DESC, al.event_id DESC
  LIMIT 1;

  NEW.hash := encode(
    digest(public.audit_log_hash_payload(NEW::public.audit_logs), 'sha256'),
    'hex'
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER audit_logs_hash_before_insert
BEFORE INSERT ON public.audit_logs
FOR EACH ROW EXECUTE FUNCTION public.audit_logs_set_hash();

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY audit_logs_service_insert ON public.audit_logs
FOR INSERT WITH CHECK ((SELECT auth.role()) = 'service_role');

CREATE POLICY audit_logs_service_select ON public.audit_logs
FOR SELECT USING ((SELECT auth.role()) = 'service_role');

CREATE POLICY audit_logs_tenant_select ON public.audit_logs
FOR SELECT USING (
  tenant_id = public.get_tenant_id()
);

-- 不建立 UPDATE / DELETE policy。必要修復只走 versioned migration 或 service repair runbook。
-- 若 consumer 尚未有 public.get_tenant_id()，請改成該專案的 tenant resolver，
-- 或在 single-tenant consumer 移除此 tenant select policy。

-- Chain verifier 樣板：
--
-- WITH ordered AS (
--   SELECT tenant_id, event_id, prev_hash, hash,
--          lag(hash) OVER (PARTITION BY tenant_id ORDER BY created_at, event_id) AS expected_prev
--   FROM public.audit_logs
-- )
-- SELECT *
-- FROM ordered
-- WHERE prev_hash IS DISTINCT FROM expected_prev
--   AND prev_hash IS NOT NULL;
--
-- 若回傳任何 row，代表 per-tenant chain 中至少有一段 prev_hash 不連續。
