import { defineConfig } from 'vite-plus'

export default defineConfig({
  test: {
    exclude: ['e2e/**', 'node_modules/**', '.nuxt/**', '.output/**'],
    coverage: {
      provider: 'v8',
    },
  },
  lint: {
    categories: {
      correctness: 'error',
      suspicious: 'warn',
      pedantic: 'off',
      perf: 'warn',
      style: 'off',
      restriction: 'off',
      nursery: 'off',
    },
    rules: {
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-alert': 'error',
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-undef': 'error',
      eqeqeq: ['error', 'always'],
    },
    plugins: ['typescript', 'unicorn', 'import', 'promise'],
    env: {
      browser: true,
      node: true,
      es2024: true,
    },
    globals: {
      // Nuxt auto-imports
      defineNuxtConfig: 'readonly',
      defineNuxtPlugin: 'readonly',
      defineNuxtRouteMiddleware: 'readonly',
      defineEventHandler: 'readonly',
      definePageMeta: 'readonly',
      definePage: 'readonly',
      defineAppConfig: 'readonly',
      defineProps: 'readonly',
      defineEmits: 'readonly',
      defineModel: 'readonly',
      defineExpose: 'readonly',
      defineSlots: 'readonly',
      defineOptions: 'readonly',
      withDefaults: 'readonly',
      useRuntimeConfig: 'readonly',
      useRoute: 'readonly',
      useRouter: 'readonly',
      useState: 'readonly',
      useFetch: 'readonly',
      useAsyncData: 'readonly',
      useLazyFetch: 'readonly',
      useLazyAsyncData: 'readonly',
      useNuxtApp: 'readonly',
      useHead: 'readonly',
      useSeoMeta: 'readonly',
      navigateTo: 'readonly',
      createError: 'readonly',
      clearError: 'readonly',
      showError: 'readonly',
      clearNuxtData: 'readonly',
      refreshNuxtData: 'readonly',
      setPageLayout: 'readonly',
      setResponseStatus: 'readonly',
      prerenderRoutes: 'readonly',
      abortNavigation: 'readonly',
      addRouteMiddleware: 'readonly',
      defineNuxtComponent: 'readonly',
      useAppConfig: 'readonly',
      updateAppConfig: 'readonly',
      useError: 'readonly',
      useRequestEvent: 'readonly',
      useRequestFetch: 'readonly',
      useRequestHeaders: 'readonly',
      useRequestURL: 'readonly',
      useCookie: 'readonly',
      refreshCookie: 'readonly',
      onNuxtReady: 'readonly',
      callOnce: 'readonly',
      $fetch: 'readonly',
      // Vue reactivity
      ref: 'readonly',
      reactive: 'readonly',
      computed: 'readonly',
      watch: 'readonly',
      watchEffect: 'readonly',
      onMounted: 'readonly',
      onUnmounted: 'readonly',
      onBeforeMount: 'readonly',
      onBeforeUnmount: 'readonly',
      nextTick: 'readonly',
      toRef: 'readonly',
      toRefs: 'readonly',
      unref: 'readonly',
      isRef: 'readonly',
      shallowRef: 'readonly',
      triggerRef: 'readonly',
      customRef: 'readonly',
      toRaw: 'readonly',
      markRaw: 'readonly',
      provide: 'readonly',
      inject: 'readonly',
      useTemplateRef: 'readonly',
      useId: 'readonly',
      useAttrs: 'readonly',
      useSlots: 'readonly',
      useCssModule: 'readonly',
      useCssVars: 'readonly',
      onActivated: 'readonly',
      onDeactivated: 'readonly',
      onServerPrefetch: 'readonly',
      onErrorCaptured: 'readonly',
      onRenderTracked: 'readonly',
      onRenderTriggered: 'readonly',
      effectScope: 'readonly',
      getCurrentScope: 'readonly',
      onScopeDispose: 'readonly',
      readonly: 'readonly',
      shallowReactive: 'readonly',
      shallowReadonly: 'readonly',
      isProxy: 'readonly',
      isReactive: 'readonly',
      isReadonly: 'readonly',
      isShallow: 'readonly',
      toValue: 'readonly',
      // Nuxt UI / Supabase / Pinia / VueUse
      useColorMode: 'readonly',
      useToast: 'readonly',
      useSupabaseClient: 'readonly',
      useUserSession: 'readonly',
      usePiniaColada: 'readonly',
      defineStore: 'readonly',
      storeToRefs: 'readonly',
      acceptHMRUpdate: 'readonly',
      // Server utils (h3/nitro)
      getQuery: 'readonly',
      getRouterParam: 'readonly',
      getRouterParams: 'readonly',
      readBody: 'readonly',
      readValidatedBody: 'readonly',
      getValidatedQuery: 'readonly',
      getValidatedRouterParams: 'readonly',
      getHeader: 'readonly',
      getHeaders: 'readonly',
      getRequestHeader: 'readonly',
      setHeader: 'readonly',
      setHeaders: 'readonly',
      appendHeader: 'readonly',
      getCookie: 'readonly',
      setCookie: 'readonly',
      deleteCookie: 'readonly',
      sendRedirect: 'readonly',
      sendNoContent: 'readonly',
      sendError: 'readonly',
      sendStream: 'readonly',
      getRequestURL: 'readonly',
      getRequestIP: 'readonly',
      getRequestHost: 'readonly',
      getRequestProtocol: 'readonly',
      useStorage: 'readonly',
      useSession: 'readonly',
      getUserSession: 'readonly',
      setUserSession: 'readonly',
      clearUserSession: 'readonly',
      requireUserSession: 'readonly',
      defineWebSocket: 'readonly',
      defineWebSocketHandler: 'readonly',
      defineCachedFunction: 'readonly',
      defineCachedEventHandler: 'readonly',
      cachedEventHandler: 'readonly',
      defineOAuthGoogleEventHandler: 'readonly',
      defineOAuthLineEventHandler: 'readonly',
      defineOAuthGitHubEventHandler: 'readonly',
      // VueUse
      useDebounceFn: 'readonly',
      useThrottleFn: 'readonly',
      refDebounced: 'readonly',
      refThrottled: 'readonly',
      useMediaQuery: 'readonly',
      useInfiniteScroll: 'readonly',
      useScroll: 'readonly',
      useElementSize: 'readonly',
      useElementVisibility: 'readonly',
      useLocalStorage: 'readonly',
      useSessionStorage: 'readonly',
      useMouse: 'readonly',
      useClipboard: 'readonly',
      useEventListener: 'readonly',
      useOnClickOutside: 'readonly',
      useFocusTrap: 'readonly',
      // Pinia Colada
      useQuery: 'readonly',
      useMutation: 'readonly',
      useQueryCache: 'readonly',
      defineQuery: 'readonly',
      defineMutation: 'readonly',
      // Nitro
      defineNitroPlugin: 'readonly',
      // Project composables
      useAuthError: 'readonly',
      useUserRole: 'readonly',
      useUpdateProfileMutation: 'readonly',
      useMyProfileQuery: 'readonly',
      useProfileListQuery: 'readonly',
      useUserStore: 'readonly',
      // Test globals
      vi: 'readonly',
      describe: 'readonly',
      it: 'readonly',
      test: 'readonly',
      expect: 'readonly',
      beforeEach: 'readonly',
      afterEach: 'readonly',
      beforeAll: 'readonly',
      afterAll: 'readonly',
    },
    ignorePatterns: [
      'node_modules/',
      '.nuxt/',
      '.output/',
      'dist/',
      'coverage/',
      'supabase/',
      '.claude/skills/',
      '*.d.ts',
    ],
  },
  fmt: {
    semi: false,
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    trailingComma: 'es5',
    quoteProps: 'as-needed',
    arrowParens: 'always',
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'css',
    vueIndentScriptAndStyle: true,
    experimentalTailwindcss: {
      stylesheet: './app/assets/css/main.css',
      attributes: ['class'],
      functions: [],
      preserveDuplicates: false,
      preserveWhitespace: false,
    },
    experimentalSortPackageJson: {
      sortScripts: true,
    },
    ignorePatterns: [
      'coverage/**',
      '.nuxt/**',
      '.output/**',
      'dist/**',
      'node_modules/**',
      '**/database.types.ts',
      'pnpm-lock.yaml',
    ],
  },
  staged: {
    '*.{js,ts,vue}': ['vp lint --fix', 'vp fmt'],
  },
})
