// 🔒 LOCKED — managed by clade · auto-generated by sync-to-cursor; edit source in .claude/ then re-run sync
/** Check if content looks like a full page (not a component/partial) */
function isFullPage(content) {
  const stripped = content.replace(/<!--[\s\S]*?-->/g, '')
  return /<!doctype\s|<html[\s>]|<head[\s>]/i.test(stripped)
}

export { isFullPage }
