#!/usr/bin/env node
// 🔒 LOCKED — managed by clade · auto-generated by sync-to-cursor; edit source in .claude/ then re-run sync
/**
 * Loopback → Tailscale IP HTTP proxy for impeccable serve-question.
 *
 * serve-question.mjs hard-binds 127.0.0.1. That URL is unusable from another
 * tailnet node. We MUST NOT copy or patch serve-question, and we MUST NOT
 * `tailscale serve` a second HTTPS port — that replaces this node's existing
 * 443 → 8080 mapping (verified 2026-08-20).
 *
 * Bind the same port on the Tailscale IPv4 address only (not 0.0.0.0) and
 * proxy to 127.0.0.1. MagicDNS then resolves to that IP; WireGuard carries
 * the bytes. Absolute paths (/answer, /img, /heartbeat) stay at /.
 *
 *   node tailnet-proxy.mjs --start --backend-port N --key K
 *   node tailnet-proxy.mjs --stop --key K
 */
import http from 'node:http'
import { spawn, execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`)
  if (i === -1) return fallback
  const v = process.argv[i + 1]
  return v && !v.startsWith('--') ? v : fallback
}
const hasFlag = (name) => process.argv.includes(`--${name}`)

const QUESTION_DIR = path.join(process.cwd(), '.impeccable', 'questions')
const statePath = (key) => path.join(QUESTION_DIR, `${key}.tailnet.json`)

function tailscaleIPv4() {
  const out = execFileSync('tailscale', ['ip', '-4'], { encoding: 'utf8' }).trim()
  const ip = out.split(/\s+/)[0]
  if (!ip || !ip.startsWith('100.')) {
    throw new Error(`tailscale ip -4 did not return a 100.x address: ${out}`)
  }
  return ip
}

function magicDns() {
  const raw = execFileSync('tailscale', ['status', '--json'], { encoding: 'utf8' })
  const dns = JSON.parse(raw)?.Self?.DNSName || ''
  return String(dns).replace(/\.$/, '')
}

if (hasFlag('start')) {
  const backendPort = Number(arg('backend-port'))
  const key = arg('key')
  if (!backendPort || !key) {
    console.error('usage: tailnet-proxy.mjs --start --backend-port N --key K')
    process.exit(2)
  }
  const self = fileURLToPath(import.meta.url)
  const child = spawn(process.execPath, [self, '--listen', String(backendPort), '--key', key], {
    detached: true,
    stdio: 'ignore',
    cwd: process.cwd(),
  })
  child.unref()
  const deadline = Date.now() + 4000
  while (Date.now() < deadline) {
    if (fs.existsSync(statePath(key))) {
      const state = JSON.parse(fs.readFileSync(statePath(key), 'utf8'))
      console.log(`TAILSCALE URL: ${state.url}`)
      if (state.ipUrl) console.log(`TAILSCALE IP: ${state.ipUrl}`)
      process.exit(0)
    }
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 50)
  }
  console.error('tailnet-proxy: listen timed out (tailscale offline or bind failed)')
  process.exit(2)
}

if (hasFlag('stop')) {
  const key = arg('key')
  if (!key) {
    console.error('usage: tailnet-proxy.mjs --stop --key K')
    process.exit(2)
  }
  try {
    const state = JSON.parse(fs.readFileSync(statePath(key), 'utf8'))
    if (state.pid) {
      try {
        process.kill(state.pid, 'SIGTERM')
      } catch {
        /* already gone */
      }
    }
    fs.rmSync(statePath(key), { force: true })
  } catch {
    /* nothing to stop */
  }
  process.exit(0)
}

const backendPort = Number(arg('listen'))
const key = arg('key')
if (!backendPort || !key) {
  console.error('usage: tailnet-proxy.mjs --listen N --key K')
  process.exit(2)
}

let host
let dns
try {
  host = tailscaleIPv4()
  dns = magicDns()
} catch (err) {
  console.error(`tailnet-proxy: ${err.message || err}`)
  process.exit(2)
}

const server = http.createServer((req, res) => {
  const p = http.request(
    {
      hostname: '127.0.0.1',
      port: backendPort,
      path: req.url,
      method: req.method,
      headers: req.headers,
    },
    (up) => {
      res.writeHead(up.statusCode ?? 502, up.headers)
      up.pipe(res)
    },
  )
  p.on('error', () => {
    if (!res.headersSent) res.writeHead(502)
    res.end()
  })
  req.pipe(p)
})

server.on('error', (err) => {
  console.error(`tailnet-proxy listen failed: ${err.message}`)
  process.exit(2)
})

server.listen(backendPort, host, () => {
  fs.mkdirSync(QUESTION_DIR, { recursive: true })
  const ipUrl = `http://${host}:${backendPort}/`
  const url = dns ? `http://${dns}:${backendPort}/` : ipUrl
  fs.writeFileSync(
    statePath(key),
    JSON.stringify({ pid: process.pid, port: backendPort, host, url, ipUrl }),
  )
})
